import { Skill } from '../types/game';

export const SKILL_DATABASE: Skill[] = [
  // STRIKE & CRIT BUILDS
  {
    id: 'skill_flurry_master',
    name: 'Flurry Master',
    description: 'Rapid punches executed in a single continuous breath.',
    quote: '"Five punches, one breath."',
    rarity: 'epic',
    category: 'combo',
    level: 1,
    maxLevel: 5,
    iconName: 'Zap',
    bonusText: '+6% Combo Rate, +12 ATK',
    statBonus: { comboRate: 6, atk: 12 },
    specialProc: { type: 'double_strike', chance: 25, multiplier: 1.5 },
  },
  {
    id: 'skill_bicycle_thunder',
    name: 'Thunder Bicycle Kick',
    description: 'Leap into the air and deliver a devastating overhead thunder kick.',
    quote: '"Gravity is optional in this ring."',
    rarity: 'legendary',
    category: 'strike',
    level: 1,
    maxLevel: 5,
    iconName: 'Sparkles',
    bonusText: '+8% Crit Rate, +35% Crit DMG',
    statBonus: { critRate: 8, critDmg: 0.35, atk: 20 },
    specialProc: { type: 'bicycle_kick', chance: 20, multiplier: 2.2 },
  },
  {
    id: 'skill_heavy_haymaker',
    name: 'Heavy Haymaker',
    description: 'A crushing overhand hook that fractures enemy guard.',
    quote: '"One clean connection is all it takes."',
    rarity: 'rare',
    category: 'strike',
    level: 1,
    maxLevel: 5,
    iconName: 'Flame',
    bonusText: '+18 ATK, +5% Crit Rate',
    statBonus: { atk: 18, critRate: 5 },
  },

  // DEFENSE & TANK BUILDS
  {
    id: 'skill_iron_chin',
    name: 'Iron Chin',
    description: 'Hardened jaw absorbs heavy impacts without flinching.',
    quote: '"Hit me with your best shot."',
    rarity: 'rare',
    category: 'defense',
    level: 1,
    maxLevel: 5,
    iconName: 'Shield',
    bonusText: '+120 HP, +15 DEF',
    statBonus: { hp: 120, def: 15 },
    specialProc: { type: 'iron_chin', chance: 20, multiplier: 0.5 },
  },
  {
    id: 'skill_golden_guard',
    name: 'Golden Fortress',
    description: 'Impenetrable blocking stance backed by titanium spirit.',
    quote: '"Unshakable as concrete."',
    rarity: 'epic',
    category: 'defense',
    level: 1,
    maxLevel: 5,
    iconName: 'ShieldAlert',
    bonusText: '+200 HP, +25 DEF, +40 Stamina',
    statBonus: { hp: 200, def: 25, stamina: 40 },
  },

  // SPEED & DODGE BUILDS
  {
    id: 'skill_shadow_slip',
    name: 'Shadow Slip',
    description: 'Fluid head movement makes attacks graze uselessly past.',
    quote: '"Float like a feather, strike like lightning."',
    rarity: 'rare',
    category: 'speed',
    level: 1,
    maxLevel: 5,
    iconName: 'Wind',
    bonusText: '+7% Dodge Rate, +8 SPD',
    statBonus: { dodgeRate: 7, spd: 8 },
    specialProc: { type: 'shadow_dodge', chance: 20, multiplier: 1.0 },
  },
  {
    id: 'skill_counter_sniper',
    name: 'Counter Striker',
    description: 'Immediately retaliate with a punishing cross right after dodging.',
    quote: '"Miss me? Pay the toll."',
    rarity: 'legendary',
    category: 'speed',
    level: 1,
    maxLevel: 5,
    iconName: 'Crosshair',
    bonusText: '+6% Dodge Rate, +15 ATK, Counter Strike',
    statBonus: { dodgeRate: 6, atk: 15 },
    specialProc: { type: 'counter_strike', chance: 35, multiplier: 1.8 },
  },

  // LIFESTEAL & VAMPIRE BUILDS
  {
    id: 'skill_vampiric_bite',
    name: 'Vampiric Strikes',
    description: 'Absorb the opponent\'s stamina and health with every landed blow.',
    quote: '"Your pain feeds my vitality."',
    rarity: 'epic',
    category: 'lifesteal',
    level: 1,
    maxLevel: 5,
    iconName: 'HeartPulse',
    bonusText: '+5.5% Lifesteal, +60 HP',
    statBonus: { lifesteal: 5.5, hp: 60 },
    specialProc: { type: 'vampire', chance: 30, multiplier: 1.0 },
  },
  {
    id: 'skill_adrenaline_rush',
    name: 'Adrenaline Surge',
    description: 'When near low health, surge with explosive attack and speed.',
    quote: '"I can do this all day."',
    rarity: 'rare',
    category: 'rage',
    level: 1,
    maxLevel: 5,
    iconName: 'Activity',
    bonusText: '+15 ATK, +10 SPD, +50 Stamina',
    statBonus: { atk: 15, spd: 10, stamina: 50 },
  },

  // SPECIAL SOCCER / STRIKER BUILDS
  {
    id: 'skill_golden_curve',
    name: 'Curveball Volley',
    description: 'Kick with extreme spin that curves right around enemy guards.',
    quote: '"Bend physics to your will."',
    rarity: 'epic',
    category: 'strike',
    level: 1,
    maxLevel: 5,
    iconName: 'CircleDot',
    bonusText: '+6% Crit Rate, +5% Combo Rate, +14 ATK',
    statBonus: { critRate: 6, comboRate: 5, atk: 14 },
  },
  {
    id: 'skill_berserk_trance',
    name: 'Street Berserker',
    description: 'Sacrifice defense for immense raw punching and kicking destruction.',
    quote: '"All gas, no brakes."',
    rarity: 'mythic',
    category: 'rage',
    level: 1,
    maxLevel: 5,
    iconName: 'Skull',
    bonusText: '+45 ATK, +10% Crit, +10% Combo, -10 DEF',
    statBonus: { atk: 45, critRate: 10, comboRate: 10, def: -10 },
    specialProc: { type: 'execute', chance: 15, multiplier: 2.5 },
  },
  {
    id: 'skill_mach_speed',
    name: 'Mach Footwork',
    description: 'Hypersonic pivots and foot taps overwhelm slower heavyweights.',
    quote: '"Too slow to even see me."',
    rarity: 'uncommon',
    category: 'speed',
    level: 1,
    maxLevel: 5,
    iconName: 'Footprints',
    bonusText: '+12 SPD, +4% Dodge Rate',
    statBonus: { spd: 12, dodgeRate: 4 },
  },
];

export function getRandomSkill(): Skill {
  const index = Math.floor(Math.random() * SKILL_DATABASE.length);
  const base = SKILL_DATABASE[index];
  return { ...base };
}
